spring:
  application:
    name: message-api
#  cloud:
#    config:
#      enabled: false
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
message: This message is from default configuration
